app/urls.py
from django.conf.urls.static import static
from django.urls import path

from to_do_list import settings

from app.views import (
    TaskListView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    ToggleTaskStatus,
    tasks_by_tag_view,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "toggle-task-status/<int:pk>/",
        ToggleTaskStatus.as_view(),
        name="toggle-task-status",
    ),
    path("statistics/", tasks_by_tag_view, name="statistics"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "app"

to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from to_do_list import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-created_at"]

    def __str__(self):
        return self.title

app/forms.py
from django import forms

from app.models import Task, Tag


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {"deadline": forms.DateInput(attrs={"type": "date"})}

app/views.py
import datetime

from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import generic, View

from app.forms import TagForm, TaskForm
from app.models import Tag, Task

import matplotlib.pyplot as plt
from io import BytesIO
import base64


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "app/index.html"
    queryset = Task.objects.prefetch_related("tags")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        context["today_datetime"] = datetime.datetime.now()

        return context


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("app:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("app:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("app:index")


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "app/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("app:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("app:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("app:tag-list")


class ToggleTaskStatus(View):
    def post(self, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs["pk"])
        task.is_done = not task.is_done
        task.save()
        return redirect(reverse_lazy("app:index"))


plt.switch_backend("Agg")


def tasks_by_tag_view(request):
    tags = Tag.objects.all()
    tasks_count_by_tag = {tag.name: tag.tasks.count() for tag in tags}

    plt.figure(figsize=(6, 4))
    plt.bar(
        tasks_count_by_tag.keys(),
        tasks_count_by_tag.values(),
        color="skyblue"
    )
    plt.xlabel("Tags")
    plt.ylabel("Number of Tasks")

    buffer = BytesIO()
    plt.savefig(buffer, format="png")
    buffer.seek(0)
    bar_chart_png = buffer.getvalue()
    buffer.close()

    bar_chart = base64.b64encode(bar_chart_png).decode("utf-8")

    total_tasks = Task.objects.count()
    completed_tasks = Task.objects.filter(is_done=True).count()
    pending_tasks = total_tasks - completed_tasks

    plt.figure(figsize=(6, 4))
    labels = ["Completed", "Pending"]
    sizes = [completed_tasks, pending_tasks]
    colors = ["skyblue", "#FF7043"]
    explode = (0.1, 0)
    plt.pie(
        sizes,
        explode=explode,
        labels=labels,
        colors=colors,
        autopct="%1.1f%%",
        shadow=True,
        startangle=140,
    )

    buffer = BytesIO()
    plt.savefig(buffer, format="png")
    buffer.seek(0)
    pie_chart_png = buffer.getvalue()
    buffer.close()

    pie_chart = base64.b64encode(pie_chart_png).decode("utf-8")

    return render(
        request,
        "app/statistics.html",
        {
            "bar_chart": bar_chart,
            "pie_chart": pie_chart
        }
    )

templates/app/index.html
{% extends "base.html" %}

{% block content %}
    <h1>To Do List</h1>
    <button style="float: right; bottom: 50px; position: relative" class="btn btn-primary">
        <a role="button" style="color: white" href="{% url 'app:task-create' %}">Add task</a>
    </button>
    <br>

    {% if task_list %}
        <div class="overflow-auto task-list">
            {% for task in task_list %}
                <div class="form-group">
                    <b>{{ task.title }}</b>
                    {% if task.is_done %}
                        <b><span class="text-success">Done</span></b>
                        <form method="post" action="{% url 'app:toggle-task-status' pk=task.id %}" style="float: right;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary">Undo</button>
                        </form>
                    {% else %}
                        <b><span class="text-danger">Not done</span></b>
                        <form method="post" action="{% url 'app:toggle-task-status' pk=task.id %}" style="float: right;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success">Complete</button>
                        </form>
                    {% endif %}
                </div>
                <div class="form-group">
                    Created: {{ task.created_at }}
                    {% if task.deadline %}
                        <span class="text-deadline">Deadline: {{ task.deadline }}</span>
                    {% endif %}
                </div>
                <div class="form-group">
                    <span class="text-secondary"> Tags:
                        {% for tag in task.tags.all %}
                            {{ tag.name }}
                        {% endfor %}
                    </span>
                    <a href="{% url 'app:task-update' pk=task.id %}">Update</a>
                    <a href="{% url 'app:task-delete' pk=task.id %}">Delete</a>
                </div>
                <hr>
            {% endfor %}
        </div>
    {% else %}
        <p>You currently have no tasks in your list.</p>
    {% endif %}
{% endblock %}

templates/app/statistics.html
<style>
  .chart {
    display: block;
    margin-bottom: 40px;
  }
</style>
{% extends "base.html" %}

{% block title %}
<title>Tasks Statistics</title>
{% endblock %}

{% block content %}
<h1>Tasks Statistics</h1>
<hr>
<h4>Number of Tasks by Tags</h4>
<img src="data:image/png;base64,{{ bar_chart }}" alt="Tasks by Tag" class="chart">

<h4>Task Completion Status</h4>
<img src="data:image/png;base64,{{ pie_chart }}" alt="Task Completion Status" class="chart">
{% endblock %}

templates/app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
    <p>Are you sure you want to delete the tag {{ tag }}? This action cannot be undone.</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'app:tag-list' %}" class="btn btn-secondary" style="margin-left: 20px">Cancel</a>
  </form>
{% endblock %}

templates/app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} tag</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/app/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Tags list</h1>
    <button style="float: right; margin-right: 25px; bottom: 50px; position: relative;" class="btn btn-primary">
        <a role="button" style="color: white" href="{% url 'app:tag-create'%}">Add new tag</a>
    </button>

    {% if tag_list %}
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for tag in tag_list %}
                    <tr>
                        <td>{{ tag.name }}</td>
                        <td>
                            <button style="background: gray; border: none;" class="btn">
                                <a role="button" style="color: white" href="{% url 'app:tag-update' pk=tag.id %}">Update</a>
                            </button>
                        </td>
                        <td>
                            <button style="background: gray; border: none;" class="btn">
                                <a role="button" style="color: white" href="{% url 'app:tag-delete' pk=tag.id %}">Delete</a>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no tags in the tag list.</p>
    {% endif %}

{% endblock %}

templates/app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
    <p>Are you sure you want to delete the task {{ task }}? This action cannot be undone.</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'app:index' %}" class="btn btn-secondary" style="margin-left: 20px">Cancel</a>
  </form>
{% endblock %}

templates/app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} task</h1>
    {{ form.media }}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form | crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
            crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body class="m-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                {% include "includes/sidebar.html" %}
                {% endblock %}
            </div>
            <div class="col-sm-10">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item text-primary"><a href="{% url 'app:index' %}">Home</a></li>
  <li class="list-group-item text-primary"><a href="{% url 'app:tag-list' %}">Tags</a></li>
  <li class="list-group-item text-primary"><a href="{% url 'app:statistics' %}">Statistics</a></li>
</ul>